#---- PARTIE 3 : BDD
#
#---- Creation Instance base de donnee Master et Replica
  DBMaster:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      Engine: MySQL
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      EngineVersion: 5.7
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Port: 3306
      DBInstanceIdentifier: BDMaster
      DBSubnetGroupName: !Ref DBSousReseau
      PubliclyAccessible: false      
      DBName: !Ref DBName
      VPCSecurityGroups:
      - Fn::GetAtt: [RDSSecurityGroup, GroupId]
      Tags:
        - Key: Name
          Value: DBMaster
#---- Serveur base de donnee Replica       
  DBReplica:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: DBReplica
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      SourceDBInstanceIdentifier: !Ref DBMaster     
      Tags:
        - Key: Name
          Value: DBReplica
          
          
          
