#---- PARTIE 6 : VPN
#
#------ Creation du client VPN ------          
  InfraVPN:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      Monitoring: 'true'
      NetworkInterfaces: 
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: "0"
        GroupSet:
          - !Ref SSHSecurityGroup
          - !Ref VPNSecurityGroup 
        SubnetId: 
          !Ref PrivateSubnetA
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: NetworkKey
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          apt-get update && sudo apt-get upgrade -y
          cat >> /etc/sysctl.conf << EOF
          net.ipv4.ip_forward = 1
          net.ipv6.conf.all.forwarding = 1
          EOF
          sysctl -p /etc/sysctl.conf
          apt-get install strongswan libcharon-extra-plugins strongswan-pki -y
          ipsec pki --gen --size 4096 --type rsa --outform pem > ca.key.pem
          ipsec pki --self --in ca.key.pem --type rsa --dn "CN=VPN Server CA" --ca --lifetime 3650 --outform pem > ca.cert.pem
          ipsec pki --gen --size 4096 --type rsa --outform pem > server.key.pem
          ipsec pki --pub --in server.key.pem --type rsa | ipsec pki --issue --lifetime 2750 --cacert ca.cert.pem --cakey ca.key.pem --dn "CN=18.134.226.162" --san="18.134.226.162" --flag serverAuth --flag ikeIntermediate --outform pem > server.cert.pem
          mv ca.cert.pem /etc/ipsec.d/cacerts/
          mv server.cert.pem /etc/ipsec.d/certs/
          mv ca.key.pem /etc/ipsec.d/private/
          mv server.key.pem /etc/ipsec.d/private/
          mv /etc/ipsec.conf /etc/ipsec.conf.save
          cat >> /etc/ipsec.conf << EOF
          config setup
                charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"
                strictcrlpolicy=no
                uniqueids=yes 
                cachecrls=no

          conn ipsec-ikev2-vpn 
                auto=add 
                compress=no
                type=tunnel  
                keyexchange=ikev2 
                fragmentation=yes
                forceencaps=yes
                dpdaction=clear 
                dpddelay=300s
                rekey=no
                left=${IPElasticIntranet} 
                leftid=18.134.226.162 
                leftcert=server.cert.pem
                leftsendcert=always
                leftsubnet=${PrivateSubnetA} 
                right=${IPPublicDistant} 
                rightid=${IPPublicDistant}
                rightsubnet=${ReseauLocalDistant}
                rightauth=eap-mschapv2
                rightsourceip=172.16.0.0/16  
                rightdns=8.8.8.8,8.8.4.4 
                rightsendcert=never
                eap_identity=%identity         
          EOF
          cat >> /etc/ipsec.secrets << EOF
          : RSA "server.key.pem"
          .vpnsecure : EAP "P@$$w0rdEd10"
          EOF
          systemctl restart strongswan
          systemctl enable strongswan
          cat > /etc/rc.local << EOF
          #! /bin/bash
          echo 1 > /proc/sys/net/ipv4/ip_forward
          iptables -t nat -A POSTROUTING -s 10.0.10.0/24 -o eth0 -m policy --dir out --pol ipsec -j ACCEPT
          iptables -t nat -A POSTROUTING -s 10.0.10.0/24 -o eth0 -j MASQUERADE
          iptables -t nat -I POSTROUTING -m policy --pol ipsec --dir out -j ACCEPT
          iptables -A INPUT -p UDP --dport 500 -j ACCEPT
          iptables -A INPUT -p UDP --dport 4500 -j ACCEPT
          exit 0
          EOF
          chmod 755 /etc/rc.local
          systemctl enable --now strongswan.service
          ipsec reload
      Tags:
        - Key: Name
          Value: InfraVPN
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
            
            
